name: Print Job Summary
on:
  push:
    branches:
      - '**'
jobs:
  JFrog-Job-Summary:
    strategy:
      matrix:
        os: [ ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Generic build
        run: |
          jf rt u ./README generic-local-robi/ --module=generic-module
      - name: Publish build info
        run: |
          jf rt bce
          jf rt bp