name: "Multi config test"

on: push

env:
  JFROG_CLI_LOG_LEVEL: DEBUG

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read
  security-events: write
jobs:
  Python-Tests:
    name: ${{ matrix.os }}
    strategy:
      #fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: RobiNino/setup-jfrog-cli@multi-config
        #id: setup-cli
        env:
          JF_URL: ${{ vars.JF_URL_ECO }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          #JF_ACCESS_TOKEN: ${{ secrets.JF_REF_TOKEN_ECO }}
        #with:
        #  version: 2.67.0
        #  # OIDC provider name from the OIDC integration page in the JFrog Platform
        #  #oidc-provider-name: robi-oidc-test-groups

      - name: Check
        run: |
          jf rt ping
          jf c show
          echo $SETUP_JFROG_CLI_SERVER_IDS
