name: "Multi config test"

on: push

env:
  JFROG_CLI_LOG_LEVEL: DEBUG

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read
  security-events: write
jobs:
  Tests:
    name: ${{ matrix.os }}
    strategy:
      #fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI 1
        uses: RobiNino/setup-jfrog-cli@multi-config
        env:
          JF_URL: ${{ vars.JF_URL_ECO }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

      - name: Setup JFrog CLI 2
        uses: RobiNino/setup-jfrog-cli@multi-config
        env:
          JF_URL: ${{ vars.JF_URL_ECO }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        with:
          custom-server-id: "my-server-2"

      - name: Setup JFrog CLI 3
        uses: RobiNino/setup-jfrog-cli@multi-config
        env:
          JF_URL: ${{ vars.JF_URL_ECO }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        with:
          custom-server-id: "my-server-3"

      - name: Check
        run: |
          jf rt ping
          jf c show
          echo "SETUP_JFROG_CLI_SERVER_IDS:"
          echo $SETUP_JFROG_CLI_SERVER_IDS

      - name: Check 2
        run: |
          jf rt ping --server-id=my-server-2
          jf c show
          echo "SETUP_JFROG_CLI_SERVER_IDS:"
          echo $SETUP_JFROG_CLI_SERVER_IDS
