name: "JFrog CLI Example"
on: push

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ ubuntu, macos ]
        node: [ "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" ]
    #runs-on: ${{ matrix.os }}-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          #JF_URL: ${{ vars.JF_URL }}
          #JF_USER: ${{ secrets.JF_USER }}
          #JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          #JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        with:
          # OIDC provider name from the OIDC integration page in the JFrog Platform
          oidc-provider-name: robi-oidc-test-groups
          version: latest
          #version: 2.100.0
          #download-repository: generic-local-robi
      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Run JFrog CLI
        run: |
          node -v
          npm -v
          jf -v
          jf rt dl generic-local-robi/v2/2.100.0/jfrog-cli-linux-amd64/jfrog --flat --fail-no-op
          chmod +x ./jfrog
          ./jfrog -v
          # Ping the server
          ./jfrog rt ping
          # Collect environment variables for the build
           
           
          cd npm-example
          #npm login --registry=https://ecosysjfrog.jfrog.io/artifactory/api/npm/npm-remote/ --auth-type=legacy
          #cd npmpostinstall
          ../jfrog npm-config --repo-resolve npm-remote
          ../jfrog npm i
          ../jfrog rt bp
          
          #cd npmpostinstall
          #cd npm-example
          #jf npm-config --repo-resolve npm-remote
          #jf npm i
          #jf rt bp
                    
          
          #cd yarn-examples
          #cd yarn-berry
          #../../jfrog yarn-config --repo-resolve npm-remote
          #../../jfrog yarn install
          #../../jfrog rt bp