name: "JobSummaries"
on: push

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  DOCKER_REPO: docker-local
  IMAGE_NAME: swampapp
  JF_URL: https://${{ vars.JF_URL_ECO_DOCKER }}/
  JFROG_CLI_LOG_LEVEL: DEBUG
  DOCKER_BUILD_SUMMARY: false
  DOCKER_BUILD_RECORD_UPLOAD: false

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Checkout different repository
        uses: actions/checkout@v4
        with:
          repository: RobiNino/jfrog-cli
          ref: sarif-support
          # token: ${{ secrets.GITHUB_TOKEN }}
          path: custom-jf

      - name: Build custom JFrog CLI
        run: |
          cd custom-jf
          ./build/build.sh
          chmod +x ./jf

      - name: Setup JFrog CLI
        #uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        #uses: jfrog/setup-jfrog-cli@master
        uses: jfrog/setup-jfrog-cli@master
        env:
          #JFROG_CLI_BUILD_NAME: "custom build name"
          #JFROG_CLI_BUILD_NUMBER: "123"
          JF_URL_ECO_DOCKER: ${{ vars.JF_URL_ECO_DOCKER_ECO }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #JF_PROJECT: "robip"
          #JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        with:
          download-repository: generic-local-robi
          #version: 2.59.1
        #  # OIDC provider name from the OIDC integration page in the JFrog Platform
        #  #oidc-provider-name: robi-oidc-test-groups

      - name: Set CLI Config
        run: ./custom-jf/jf npm-config --global=true --repo-resolve=robi-npm --repo-deploy=robi-npm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JF_URL_ECO_DOCKER }}
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.JF_PASSWORD }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          push: true
          context: .
          file: docker-oci-examples/fat-manifest-example/Dockerfile.Fatmanifest
          platforms: linux/amd64,linux/arm64
          tags: ${{ vars.JF_URL_ECO_DOCKER }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
          provenance: false

      - name: Docker scan
        run: |
          ./custom-jf/jf docker pull ${{ vars.JF_URL_ECO_DOCKER }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
          ./custom-jf/jf docker scan ${{ vars.JF_URL_ECO_DOCKER }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest --vuln --project=${{ vars.JF_PROJECT }} --fail=false --watches=jobsummary

      - name: JF Scan
        run: |
          ./custom-jf/jf scan ./curation-project/
      #- name: add docker package to build
      #  run: |
      #    echo "${{ vars.JF_URL_ECO_DOCKER }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}" > metadata.json
      #    jf rt build-docker-create ${{ env.DOCKER_REPO }} --image-file metadata.json
      #- name: Generic build
      #  run: |
      #    cd bash-example
      #    jf rt u ./deploy-file.sh generic-local/ --module=generic-module
      #- name: Npm curation
      #  run: |
      #    cd npm-example
      #    jf ca
      #- name: publish build info
      #  if: always()
      #  run: |
      #    jf rt build-collect-env
      #    jf rt build-add-git
      #    jf rt build-publish
      #- name: build scan
      #  if : always()
      #  run: |
      #    jf build-scan --vuln --fail=false